Resources:
    MyVPC:
      Type: AWS::EC2::VPC
      Properties:
        CidrBlock: "10.1.0.0/16"
        Tags:
          - Key: Name
            Value: CloudFormation VPC
    
    MyInternetGateway:
      Type: AWS::EC2::InternetGateway
      Properties:
        Tags:
          - Key: Name
            Value: CF Internet Gateway

    MyInternetGatewayAttachment:
      Type: AWS::EC2::VPCGatewayAttachment
      Properties:
        VpcId:
          Ref: MyVPC
        InternetGatewayId:
          Ref: MyInternetGateway
    
    NATElasticIP:
      Type: AWS::EC2::EIP
      Properties:
        Domain: MyVPC

    MyNATGateway:
      DependsOn: MyInternetGatewayAttachment
      Type: AWS::EC2::NatGateway
      Properties:
        AllocationId:
          Fn::GetAtt:
          - NATElasticIP
          - AllocationId
        SubnetId:
          Ref: PublicSubnet2a
        Tags:
          - Key: Name
            Value: CF NAT Gateway

    MyPublicRouteTable:
      Type: AWS::EC2::RouteTable
      Properties:  
        VpcId:
          Ref: MyVPC
        Tags:
          -  Key: Name
             Value: CF Public Route Table

    MyPrivateRouteTable:
      Type: AWS::EC2::RouteTable
      Properties:  
        VpcId:
          Ref: MyVPC
        Tags:
          -  Key: Name
             Value: CF Private Route Table

    MyPublicRoute:
      Type: AWS::EC2::Route
      DependsOn: MyInternetGatewayAttachment
      Properties:
        RouteTableId:
          Ref: MyPublicRouteTable
        DestinationCidrBlock: 0.0.0.0/0
        GatewayId:
          Ref: MyInternetGateway
    
    MyPrivateRoute:
      Type: AWS::EC2::Route
      Properties:
        RouteTableId:
          Ref: MyPrivateRouteTable
        DestinationCidrBlock: 0.0.0.0/0
        NatGatewayId:
          Ref: MyNATGateway

    PublicSubnet2a:
      Type: AWS::EC2::Subnet
      Properties:
        CidrBlock: "10.1.0.0/24"
        AvailabilityZone: "eu-west-2a"
        VpcId: 
          Ref: MyVPC
        Tags:
          - Key: Name
            Value: CF Public Subnet 2a

    PrivateSubnet2a:
      Type: AWS::EC2::Subnet
      Properties:
        CidrBlock: "10.1.1.0/24"
        AvailabilityZone: "eu-west-2a"
        VpcId: 
          Ref: MyVPC
        Tags:
          - Key: Name
            Value: CF Private Subnet 2a

    PublicSubnet2b:
      Type: AWS::EC2::Subnet
      Properties:
        CidrBlock: "10.1.2.0/24"
        AvailabilityZone: "eu-west-2b"
        VpcId: 
          Ref: MyVPC
        Tags:
          - Key: Name
            Value: CF Public Subnet 2b

    PrivateSubnet2b:
      Type: AWS::EC2::Subnet
      Properties:
        CidrBlock: "10.1.3.0/24"
        AvailabilityZone: "eu-west-2b"
        VpcId: 
          Ref: MyVPC
        Tags:
          - Key: Name
            Value: CF Private Subnet 2b

    MyVPNSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: Security group for OpenVPN Server
        VpcId: 
          Ref: MyVPC
        SecurityGroupIngress:
          - IpProtocol: TCP
            FromPort: 22
            ToPort: 22
            CidrIp: 185.73.154.30/32
          - IpProtocol: TCP
            FromPort: 443
            ToPort: 443
            CidrIp: 185.73.154.30/32
          - IpProtocol: TCP
            FromPort: 943
            ToPort: 943
            CidrIp: 185.73.154.30/32
          - IpProtocol: UDP
            FromPort: 1194
            ToPort: 1194
            CidrIp: 185.73.154.30/32
    
    MyVPNServer:
      Type: AWS::EC2::Instance
      Properties:
        InstanceType: t2.micro
        ImageId: "ami-04c453c26f35557e4"
        KeyName: "TechLabsKey"
        SecurityGroupIds:
        - Ref: MyVPNSecurityGroup
        SubnetId:
          Ref: PublicSubnet2a



